### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by Schnark** [radare/fxos-app-ruler#1]
I'd like to reuse some parts of your ruler app. Unfortunately, you don't say whether it is available under an open source license, and if so under which. So I'd be glad if you could add a license file to the repository (or just state it here).

**Comment by radare** [comment]
Feel free to reuse anything. I would license it under MIT. You are welcome

**Comment by Schnark** [comment]
Thank you very much!

**Comment by radare** [comment]
fixed in a2986b0d2e2767e84e867ab5ecc73205e61bbc74
